FROM python:3.13-slim

WORKDIR /app

COPY req_admin.txt ./
RUN pip install --no-cache-dir -r req_admin.txt

COPY . /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]
